export const actors = [
  {id: 1, name: "Уилл Смит"},
  {id: 2, name: "Джейден Смит"},
  {id: 3, name: "Роберт Дауни мл."},
  {id: 4, name: "Крис Эванс"},
  {id: 5, name: "Марк Руффало"},
  {id: 6, name: "Крис Хемсворт"},
  {id: 7, name: "Милош Бикович"},
  {id: 8, name: "Александра Бортич"},
  {id: 9, name: "Иван Охлобыстин"},
  {id: 10, name: "Патрик Уилсон"},
  {id: 11, name: "Лин Шэй"},
  {id: 12, name: "Роуз Бирн"},
  {id: 13, name: "Риналь Мухаметов"},
  {id: 14, name: "Ян Цапник"},
];

export const genres = [
  {id: 1, genre: "драма"},
  {id: 2, genre: "биография"},
  {id: 3, genre: "фантастика"},
  {id: 4, genre: "боевик"},
  {id: 5, genre: "приключения"},
  {id: 6, genre: "комедия"},
  {id: 7, genre: "ужасы"},
  {id: 8, genre: "триллер"},
  {id: 9, genre: "мелодрама"},
]

export const filmes = [
  {
    id: 1,
    name: "В погоне за счастьем",
    image: "https://upload.wikimedia.org/wikipedia/ru/3/3e/Pursuit_happyness_poster.jpg",
    director: "Габриэле Муччино",
    genres: [1, 2],
    actors: [1, 2],
    publishYear: 2006,
  },
  {
    id: 2,
    name: "Мстители: Финал",
    image: "https://upload.wikimedia.org/wikipedia/ru/a/a4/The_Avengers_Endgame_Poster.jpg",
    director: "Джо Руссо",
    genres: [3, 4, 1, 5],
    actors: [3, 4, 5, 6],
    publishYear: 2019,
  },
  {
    id: 3,
    name: "Холоп",
    image: "https://upload.wikimedia.org/wikipedia/ru/d/d7/%D0%A5%D0%BE%D0%BB%D0%BE%D0%BF_%28%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%29.jpg",
    director: "Клим Шипенко",
    genres: [6],
    actors: [7, 8, 9],
    publishYear: 2019,
  },
  {
    id: 4,
    name: "Астрал",
    image: "https://upload.wikimedia.org/wikipedia/ru/thumb/6/61/Insidious_2011.jpg/200px-Insidious_2011.jpg",
    director: "Джеймс Ван",
    genres: [7, 8],
    actors: [10, 11, 12],
    publishYear: 2010,
  },
  {
    id: 5,
    name: "Временные трудности",
    image: "https://upload.wikimedia.org/wikipedia/ru/4/43/%D0%92%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5_%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%BE%D1%81%D1%82%D0%B8.jpg",
    director: "Михаил Расходников",
    genres: [1, 9],
    actors: [13, 9, 14],
    publishYear: 2018,
  },
];